{{- if (not .Values.kafkaConnectorSecrets.existingSecrets) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openfaas-kafka-connector.app-secrets-name" . | quote }}
  labels:
{{ include "openfaas-kafka-connector.labels" . | indent 4 }}
data:
  {{- range $key, $value := .Values.kafkaConnectorSecrets.values }}
  {{- if eq $key "redis-pass" }}
  {{ $key }}: {{ $value | b64enc }}
  {{- else }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
